/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zengge_nbmanager_Features */

#ifndef _Included_com_zengge_nbmanager_Features
#define _Included_com_zengge_nbmanager_Features
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zengge_nbmanager_Features
 * Method:    ExtractAllRAR
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zengge_nbmanager_Features_ExtractAllRAR
(JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_zengge_nbmanager_Features
 * Method:    Oat2Dex
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zengge_nbmanager_Features_Oat2Dex
(JNIEnv *, jclass, jstring);

/*
 * Class:     com_zengge_nbmanager_Features
 * Method:    printLog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_zengge_nbmanager_Features_printLog
(JNIEnv *, jclass, jstring, jstring, jboolean);

/*
 * Class:     com_zengge_nbmanager_Features
 * Method:    Odex2Dex
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zengge_nbmanager_Features_Odex2Dex
(JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_zengge_nbmanager_Features
 * Method:    ZipAlign
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zengge_nbmanager_Features_ZipAlign
(JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_zengge_nbmanager_Features
 * Method:    isZipAligned
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zengge_nbmanager_Features_isZipAligned
(JNIEnv *, jclass, jstring);

/*
 * Class:     com_zengge_nbmanager_Features
 * Method:    isValidElf
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zengge_nbmanager_Features_isValidElf
(JNIEnv *, jclass, jstring);

/*
 * Class:     com_zengge_nbmanager_Features
 * Method:    compressStrToInt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zengge_nbmanager_Features_compressStrToInt
(JNIEnv *, jclass, jstring);

/*
 * Class:     com_zengge_nbmanager_Features
 * Method:    ELFHash
 * Signature: (Ljava/lang/String;)J;
 */
JNIEXPORT jlong JNICALL Java_com_zengge_nbmanager_Features_ELFHash
(JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
